-- MySQL Script generated by MySQL Workbench
-- Sat Nov 20 21:55:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema catalogue
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `catalogue` ;

-- -----------------------------------------------------
-- Schema catalogue
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `catalogue` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
SHOW WARNINGS;
USE `catalogue` ;

-- -----------------------------------------------------
-- Table `catalogue`.`Strategic Priority`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogue`.`Strategic Priority` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `catalogue`.`Strategic Priority` (
  `Strat_Priority_Name` VARCHAR(45) NOT NULL,
  `Strat_Priority_ID` INT NOT NULL,
  PRIMARY KEY (`Strat_Priority_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `catalogue`.`KPI_Owner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogue`.`KPI_Owner` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `catalogue`.`KPI_Owner` (
  `KPI_Owner_ID` INT NOT NULL,
  `KPI_Owner_Name` VARCHAR(45) NOT NULL,
  `KPI_Owner_Email` VARCHAR(45) NULL DEFAULT NULL,
  `KPI_Owner_Phone` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`KPI_Owner_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `catalogue`.`KPI`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogue`.`KPI` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `catalogue`.`KPI` (
  `KPI_ID` INT NOT NULL AUTO_INCREMENT,
  `KPI_Name` VARCHAR(45) NOT NULL,
  `KPI_Owner_ID` INT NOT NULL,
  `KPI_Description` VARCHAR(45) NULL DEFAULT NULL,
  `Dataset_ID` INT NULL DEFAULT NULL,
  `Permission_Status` VARCHAR(45) NULL DEFAULT NULL,
  `Strat_Priority_ID` INT NOT NULL,
  PRIMARY KEY (`KPI_ID`, `KPI_Owner_ID`),
  CONSTRAINT `Strat_Priority_ID`
    FOREIGN KEY ()
    REFERENCES `catalogue`.`Strategic Priority` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `KPI_Owner_ID`
    FOREIGN KEY (`KPI_Owner_ID`)
    REFERENCES `catalogue`.`KPI_Owner` (`KPI_Owner_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `KPI_Owner_ID_idx` ON `catalogue`.`KPI` (`KPI_Owner_ID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `catalogue`.`Dataset_Owner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogue`.`Dataset_Owner` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `catalogue`.`Dataset_Owner` (
  `Dataset_Owner_ID` INT NOT NULL,
  `Dataset_Owner_Name` VARCHAR(45) NOT NULL,
  `Dataset_Owner_Email` VARCHAR(45) NULL DEFAULT NULL,
  `Dataset_Owner_Phone` VARCHAR(45) NULL DEFAULT NULL,
  `Dataset_Owner_Dept` VARCHAR(45) NULL DEFAULT NULL,
  `Dataset_ID` INT NOT NULL,
  `Dataset_Steward_ID` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Dataset_Owner_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `catalogue`.`Dataset_Steward`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogue`.`Dataset_Steward` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `catalogue`.`Dataset_Steward` (
  `Dataset_Steward_ID` INT NOT NULL,
  `Dataset_Steward_Name` VARCHAR(45) NOT NULL,
  `Dataset_ID` INT NOT NULL,
  `Dataset_Owner_Name` VARCHAR(45) NULL DEFAULT NULL,
  `Dataset_Steward_Phone` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Dataset_Steward_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `catalogue`.`Dataset`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogue`.`Dataset` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `catalogue`.`Dataset` (
  `Dataset_ID` INT NOT NULL,
  `Dataset_Name` VARCHAR(45) NOT NULL,
  `Dataset_Owner_ID` INT NOT NULL,
  `Dataset_Steward_ID` INT NULL DEFAULT NULL,
  `Internal_External` VARCHAR(45) NULL,
  PRIMARY KEY (`Dataset_ID`),
  CONSTRAINT `Dataset_ID`
    FOREIGN KEY (`Dataset_ID`)
    REFERENCES `catalogue`.`KPI` (`KPI_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Dataset_ID`
    FOREIGN KEY (`Dataset_ID`)
    REFERENCES `catalogue`.`Dataset_Owner` (`Dataset_Owner_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Dataset_ID`
    FOREIGN KEY (`Dataset_ID`)
    REFERENCES `catalogue`.`Dataset_Steward` (`Dataset_Steward_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `catalogue`.`Permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogue`.`Permission` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `catalogue`.`Permission` (
  `Permission_ID` INT NOT NULL,
  `Permission_Status` VARCHAR(45) NULL DEFAULT NULL,
  `User_ID` INT NULL DEFAULT NULL,
  `Dataset_ID` INT NOT NULL,
  `Dataset_Owner_ID` INT NOT NULL,
  `Dataset_Steward_ID` INT NOT NULL DEFAULT NULL,
  `Date_Granted` DATETIME NULL DEFAULT NULL,
  `Date_Expires` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`Permission_ID`, `Dataset_Owner_ID`, `Dataset_Steward_ID`),
  CONSTRAINT `Dataset_Owner_ID`
    FOREIGN KEY (`Dataset_Owner_ID`)
    REFERENCES `catalogue`.`Dataset_Owner` (`Dataset_Owner_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Dataset_Steward_ID`
    FOREIGN KEY (`Dataset_Steward_ID`)
    REFERENCES `catalogue`.`Dataset_Steward` (`Dataset_Steward_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `Data_Owner_ID_idx` ON `catalogue`.`Permission` (`Dataset_Owner_ID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `Dataset_Steward_ID_idx` ON `catalogue`.`Permission` (`Dataset_Steward_ID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `catalogue`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogue`.`User` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `catalogue`.`User` (
  `User_ID` INT NOT NULL,
  `User_Name` VARCHAR(45) NULL DEFAULT NULL,
  `Permission_ID` INT NOT NULL DEFAULT NULL,
  `User_Phone` VARCHAR(45) NULL DEFAULT NULL,
  `User_Email` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`User_ID`, `Permission_ID`),
  CONSTRAINT `Permisson_ID`
    FOREIGN KEY (`Permission_ID`)
    REFERENCES `catalogue`.`Permission` (`Permission_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `Permisson_ID_idx` ON `catalogue`.`User` (`Permission_ID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Data for table `catalogue`.`Strategic Priority`
-- -----------------------------------------------------
START TRANSACTION;
USE `catalogue`;
INSERT INTO `catalogue`.`Strategic Priority` (`Strat_Priority_Name`, `Strat_Priority_ID`) VALUES ('Enhance Customer Experience', DEFAULT);
INSERT INTO `catalogue`.`Strategic Priority` (`Strat_Priority_Name`, `Strat_Priority_ID`) VALUES ('Optimize Infrastructure', DEFAULT);
INSERT INTO `catalogue`.`Strategic Priority` (`Strat_Priority_Name`, `Strat_Priority_ID`) VALUES ('Protect Our Resources', DEFAULT);
INSERT INTO `catalogue`.`Strategic Priority` (`Strat_Priority_Name`, `Strat_Priority_ID`) VALUES ('Spend Customer Dollars Wisely', DEFAULT);
INSERT INTO `catalogue`.`Strategic Priority` (`Strat_Priority_Name`, `Strat_Priority_ID`) VALUES ('Transform Employee Engagement', DEFAULT);
INSERT INTO `catalogue`.`Strategic Priority` (`Strat_Priority_Name`, `Strat_Priority_ID`) VALUES (DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `catalogue`.`KPI`
-- -----------------------------------------------------
START TRANSACTION;
USE `catalogue`;
INSERT INTO `catalogue`.`KPI` (`KPI_ID`, `KPI_Name`, `KPI_Owner_ID`, `KPI_Description`, `Dataset_ID`, `Permission_Status`, `Strat_Priority_ID`) VALUES (CIKPI01, 'Asset Management', DEFAULT, NULL, NULL, NULL, DEFAULT);
INSERT INTO `catalogue`.`KPI` (`KPI_ID`, `KPI_Name`, `KPI_Owner_ID`, `KPI_Description`, `Dataset_ID`, `Permission_Status`, `Strat_Priority_ID`) VALUES (CIKPI02, 'Financial Assistane Flyers Distributed', DEFAULT, NULL, NULL, NULL, DEFAULT);
INSERT INTO `catalogue`.`KPI` (`KPI_ID`, `KPI_Name`, `KPI_Owner_ID`, `KPI_Description`, `Dataset_ID`, `Permission_Status`, `Strat_Priority_ID`) VALUES (CIKPI03, 'Water Quality Tests', DEFAULT, NULL, NULL, NULL, DEFAULT);

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
